package net.gmsgarcia.compress.content;

import static net.gmsgarcia.compress.content.BlockFamilies.*;

import java.util.List;

  /**
   * Every Compress 'em block, in 1.17 registration order.
   *
   * <p>This list is the compatibility contract. Ids and their order carry over
   * from 1.17 unchanged, so worlds, saves and datapacks built against that
   * version still resolve. Treat any edit to it as a deliberate change rather
   * than a refactor.
   */
public final class CompressBlocks {

    public record Entry(String id, BlockSpec spec) {
    }

    public static final List<Entry> ALL = List.of(
        // compressed_dirt             tiers 1-5  DIRT,
        entry("compressed_dirt_1", DIRT),
        entry("compressed_dirt_2", DIRT),
        entry("compressed_dirt_3", DIRT),
        entry("compressed_dirt_4", DIRT),
        entry("compressed_dirt_5", DIRT),
        // compressed_sand             tiers 1-5  FALLING_SAND,
        entry("compressed_sand_1", FALLING_SAND),
        entry("compressed_sand_2", FALLING_SAND),
        entry("compressed_sand_3", FALLING_SAND),
        entry("compressed_sand_4", FALLING_SAND),
        entry("compressed_sand_5", FALLING_SAND),
        // compressed_red_sand         tiers 1-5  FALLING_SAND,
        entry("compressed_red_sand_1", FALLING_SAND),
        entry("compressed_red_sand_2", FALLING_SAND),
        entry("compressed_red_sand_3", FALLING_SAND),
        entry("compressed_red_sand_4", FALLING_SAND),
        entry("compressed_red_sand_5", FALLING_SAND),
        // compressed_gravel           tiers 1-5  FALLING_GRAVEL,
        entry("compressed_gravel_1", FALLING_GRAVEL),
        entry("compressed_gravel_2", FALLING_GRAVEL),
        entry("compressed_gravel_3", FALLING_GRAVEL),
        entry("compressed_gravel_4", FALLING_GRAVEL),
        entry("compressed_gravel_5", FALLING_GRAVEL),
        // compressed_stone            tiers 1-5  GENERIC_STONE,
        entry("compressed_stone_1", GENERIC_STONE),
        entry("compressed_stone_2", GENERIC_STONE),
        entry("compressed_stone_3", GENERIC_STONE),
        entry("compressed_stone_4", GENERIC_STONE),
        entry("compressed_stone_5", GENERIC_STONE),
        // compressed_cobblestone      tiers 1-5  COBBLESTONE,
        entry("compressed_cobblestone_1", COBBLESTONE),
        entry("compressed_cobblestone_2", COBBLESTONE),
        entry("compressed_cobblestone_3", COBBLESTONE),
        entry("compressed_cobblestone_4", COBBLESTONE),
        entry("compressed_cobblestone_5", COBBLESTONE),
        // compressed_andesite         tiers 1-5  GENERIC_STONE,
        entry("compressed_andesite_1", GENERIC_STONE),
        entry("compressed_andesite_2", GENERIC_STONE),
        entry("compressed_andesite_3", GENERIC_STONE),
        entry("compressed_andesite_4", GENERIC_STONE),
        entry("compressed_andesite_5", GENERIC_STONE),
        // compressed_diorite          tiers 1-5  GENERIC_STONE,
        entry("compressed_diorite_1", GENERIC_STONE),
        entry("compressed_diorite_2", GENERIC_STONE),
        entry("compressed_diorite_3", GENERIC_STONE),
        entry("compressed_diorite_4", GENERIC_STONE),
        entry("compressed_diorite_5", GENERIC_STONE),
        // compressed_granite          tiers 1-5  GENERIC_STONE,
        entry("compressed_granite_1", GENERIC_STONE),
        entry("compressed_granite_2", GENERIC_STONE),
        entry("compressed_granite_3", GENERIC_STONE),
        entry("compressed_granite_4", GENERIC_STONE),
        entry("compressed_granite_5", GENERIC_STONE),
        // compressed_netherrack       tiers 1-5  NETHERRACK,
        entry("compressed_netherrack_1", NETHERRACK),
        entry("compressed_netherrack_2", NETHERRACK),
        entry("compressed_netherrack_3", NETHERRACK),
        entry("compressed_netherrack_4", NETHERRACK),
        entry("compressed_netherrack_5", NETHERRACK),
        // compressed_end_stone        tiers 1-5  END_STONE,
        entry("compressed_end_stone_1", END_STONE),
        entry("compressed_end_stone_2", END_STONE),
        entry("compressed_end_stone_3", END_STONE),
        entry("compressed_end_stone_4", END_STONE),
        entry("compressed_end_stone_5", END_STONE),
        // compressed_amethyst_block   tiers 1-5  AMETHYST,
        entry("compressed_amethyst_block_1", AMETHYST),
        entry("compressed_amethyst_block_2", AMETHYST),
        entry("compressed_amethyst_block_3", AMETHYST),
        entry("compressed_amethyst_block_4", AMETHYST),
        entry("compressed_amethyst_block_5", AMETHYST),
        // compressed_calcite          tiers 1-5  CALCITE,
        entry("compressed_calcite_1", CALCITE),
        entry("compressed_calcite_2", CALCITE),
        entry("compressed_calcite_3", CALCITE),
        entry("compressed_calcite_4", CALCITE),
        entry("compressed_calcite_5", CALCITE),
        // compressed_cobbled_deepslate tiers 1-5  COBBLED_DEEPSLATE,
        entry("compressed_cobbled_deepslate_1", COBBLED_DEEPSLATE),
        entry("compressed_cobbled_deepslate_2", COBBLED_DEEPSLATE),
        entry("compressed_cobbled_deepslate_3", COBBLED_DEEPSLATE),
        entry("compressed_cobbled_deepslate_4", COBBLED_DEEPSLATE),
        entry("compressed_cobbled_deepslate_5", COBBLED_DEEPSLATE),
        // compressed_deepslate        tiers 1-5  DEEPSLATE,
        entry("compressed_deepslate_1", DEEPSLATE),
        entry("compressed_deepslate_2", DEEPSLATE),
        entry("compressed_deepslate_3", DEEPSLATE),
        entry("compressed_deepslate_4", DEEPSLATE),
        entry("compressed_deepslate_5", DEEPSLATE),
        // compressed_dripstone_block  tiers 1-5  DRIPSTONE_BLOCK,
        entry("compressed_dripstone_block_1", DRIPSTONE_BLOCK),
        entry("compressed_dripstone_block_2", DRIPSTONE_BLOCK),
        entry("compressed_dripstone_block_3", DRIPSTONE_BLOCK),
        entry("compressed_dripstone_block_4", DRIPSTONE_BLOCK),
        entry("compressed_dripstone_block_5", DRIPSTONE_BLOCK),
        // compressed_smooth_basalt    tiers 1-5  SMOOTH_BASALT,
        entry("compressed_smooth_basalt_1", SMOOTH_BASALT),
        entry("compressed_smooth_basalt_2", SMOOTH_BASALT),
        entry("compressed_smooth_basalt_3", SMOOTH_BASALT),
        entry("compressed_smooth_basalt_4", SMOOTH_BASALT),
        entry("compressed_smooth_basalt_5", SMOOTH_BASALT),
        // compressed_tuff             tiers 1-5  TUFF,
        entry("compressed_tuff_1", TUFF),
        entry("compressed_tuff_2", TUFF),
        entry("compressed_tuff_3", TUFF),
        entry("compressed_tuff_4", TUFF),
        entry("compressed_tuff_5", TUFF),
        // compressed_coal_block       tiers 1-5  COAL_BLOCK,
        entry("compressed_coal_block_1", COAL_BLOCK),
        entry("compressed_coal_block_2", COAL_BLOCK),
        entry("compressed_coal_block_3", COAL_BLOCK),
        entry("compressed_coal_block_4", COAL_BLOCK),
        entry("compressed_coal_block_5", COAL_BLOCK),
        // compressed_copper_block     tiers 1-5  COPPER_BLOCK,
        entry("compressed_copper_block_1", COPPER_BLOCK),
        entry("compressed_copper_block_2", COPPER_BLOCK),
        entry("compressed_copper_block_3", COPPER_BLOCK),
        entry("compressed_copper_block_4", COPPER_BLOCK),
        entry("compressed_copper_block_5", COPPER_BLOCK),
        // compressed_iron_block       tiers 1-5  IRON_BLOCK,
        entry("compressed_iron_block_1", IRON_BLOCK),
        entry("compressed_iron_block_2", IRON_BLOCK),
        entry("compressed_iron_block_3", IRON_BLOCK),
        entry("compressed_iron_block_4", IRON_BLOCK),
        entry("compressed_iron_block_5", IRON_BLOCK),
        // compressed_lapis_block      tiers 1-5  LAPIS_BLOCK,
        entry("compressed_lapis_block_1", LAPIS_BLOCK),
        entry("compressed_lapis_block_2", LAPIS_BLOCK),
        entry("compressed_lapis_block_3", LAPIS_BLOCK),
        entry("compressed_lapis_block_4", LAPIS_BLOCK),
        entry("compressed_lapis_block_5", LAPIS_BLOCK),
        // compressed_redstone_block   tiers 1-5  REDSTONE_BLOCK,
        entry("compressed_redstone_block_1", REDSTONE_BLOCK),
        entry("compressed_redstone_block_2", REDSTONE_BLOCK),
        entry("compressed_redstone_block_3", REDSTONE_BLOCK),
        entry("compressed_redstone_block_4", REDSTONE_BLOCK),
        entry("compressed_redstone_block_5", REDSTONE_BLOCK),
        // compressed_gold_block       tiers 1-5  GOLD_BLOCK,
        entry("compressed_gold_block_1", GOLD_BLOCK),
        entry("compressed_gold_block_2", GOLD_BLOCK),
        entry("compressed_gold_block_3", GOLD_BLOCK),
        entry("compressed_gold_block_4", GOLD_BLOCK),
        entry("compressed_gold_block_5", GOLD_BLOCK),
        // compressed_diamond_block    tiers 1-5  GENERIC_ORE,
        entry("compressed_diamond_block_1", GENERIC_ORE),
        entry("compressed_diamond_block_2", GENERIC_ORE),
        entry("compressed_diamond_block_3", GENERIC_ORE),
        entry("compressed_diamond_block_4", GENERIC_ORE),
        entry("compressed_diamond_block_5", GENERIC_ORE),
        // compressed_emerald_block    tiers 1-5  GENERIC_ORE,
        entry("compressed_emerald_block_1", GENERIC_ORE),
        entry("compressed_emerald_block_2", GENERIC_ORE),
        entry("compressed_emerald_block_3", GENERIC_ORE),
        entry("compressed_emerald_block_4", GENERIC_ORE),
        entry("compressed_emerald_block_5", GENERIC_ORE)
    );

    public static List<Entry> all() {
        return ALL;
    }

    private static Entry entry(String id, BlockSpec spec) {
        return new Entry(id, spec);
    }

    private CompressBlocks() {
    }
}
